// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2T0Hq8zddNbHJgYxIsbhWaXox1MT7DY',
    appId: '1:997282997458:web:ac266af9a5254a0bbe790b',
    messagingSenderId: '997282997458',
    projectId: 'orderapplication-84073',
    authDomain: 'orderapplication-84073.firebaseapp.com',
    storageBucket: 'orderapplication-84073.appspot.com',
    measurementId: 'G-2W7L27Z2JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1lONFlBs2-TEadONAesIRT791w9uc6w',
    appId: '1:997282997458:android:9265cfc01efb406dbe790b',
    messagingSenderId: '997282997458',
    projectId: 'orderapplication-84073',
    storageBucket: 'orderapplication-84073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GeWg52xA-PMHrBQ3QDK8BaKBceQ7MIg',
    appId: '1:997282997458:ios:dd0f5fecfc914243be790b',
    messagingSenderId: '997282997458',
    projectId: 'orderapplication-84073',
    storageBucket: 'orderapplication-84073.appspot.com',
    androidClientId: '997282997458-gstitgl2dfv3dqevlrmu1hlif09vt261.apps.googleusercontent.com',
    iosClientId: '997282997458-3e408hkqenltiddq7l38u0voivfo125t.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderApp',
  );
}
